# Generated by Django 5.0.7 on 2025-10-30 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text="Короткое имя для URL (например, 'rules')", max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(help_text='Используйте HTML-теги для форматирования.', verbose_name='Содержание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам или реклама'), ('inappropriate_content', 'Неприемлемый контент (фото, текст)'), ('scam', 'Мошенничество или обман'), ('insult', 'Оскорбления или грубое поведение'), ('other', 'Другое')], max_length=50, verbose_name='Причина')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Подробное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('status', models.CharField(choices=[('new', 'Взята на расмотрение'), ('in_progress', 'Рассматривается'), ('resolved', 'Разрешённый конфликт (Одельно вы получите сообшение-отчет о жалобе)')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, на которого жалуются')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Подавший жалобу')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='profiles.complaint')),
            ],
            options={
                'verbose_name': 'Лог жалобы',
                'verbose_name_plural': 'Логи жалоб',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Симпатия',
                'verbose_name_plural': 'Симпатии',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Максимум 2000 символов', max_length=2000, verbose_name='Содержание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('is_deleted_by_sender', models.BooleanField(default=False, verbose_name='Удалено отправителем')),
                ('is_deleted_by_receiver', models.BooleanField(default=False, verbose_name='Удалено получателем')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('LIKE', 'Новая симпатия'), ('MESSAGE', 'Новое сообщение'), ('COMPLAINT_STATUS', 'Статус жалобы'), ('ADMIN', 'От администрации'), ('SYSTEM', 'Системное')], db_index=True, max_length=20, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из заголовка', max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Одобрен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='profiles.comment', verbose_name='Родительский комментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=10, null=True, verbose_name='Пол')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Город')),
                ('photo', models.ImageField(default='default-avatar.png', upload_to='profile_pics/%Y/%m/%d/', verbose_name='Фотография профиля')),
                ('about_me', models.TextField(blank=True, help_text='Максимум 2000 символов', max_length=2000, verbose_name='О себе')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100, message='Минимальный рост 100 см'), django.core.validators.MaxValueValidator(250, message='Максимальный рост 250 см')], verbose_name='Рост (см)')),
                ('marital_status', models.CharField(blank=True, choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Разведен(а)', 'Разведен(а)'), ('Вдовец/Вдова', 'Вдовец/Вдова')], max_length=50, null=True, verbose_name='Семейное положение')),
                ('children', models.CharField(blank=True, choices=[('Нет', 'Нет'), ('Есть', 'Есть')], max_length=50, null=True, verbose_name='Дети')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Профессия')),
                ('churching_level', models.CharField(blank=True, choices=[('Новоначальный', 'Новоначальный'), ('Воцерковленный', 'Воцерковленный')], db_index=True, max_length=50, null=True, verbose_name='Степень воцерковленности')),
                ('attitude_to_fasting', models.CharField(blank=True, choices=[('Соблюдаю', 'Соблюдаю'), ('Не соблюдаю', 'Не соблюдаю')], max_length=50, null=True, verbose_name='Отношение к постам')),
                ('sacraments', models.CharField(blank=True, choices=[('Регулярно', 'Регулярно'), ('Иногда', 'Иногда'), ('Редко', 'Редко')], max_length=50, null=True, verbose_name='Участие в Таинствах')),
                ('favorite_saints', models.CharField(blank=True, max_length=255, verbose_name='Любимые святые')),
                ('spiritual_books', models.TextField(blank=True, max_length=1000, verbose_name='Любимые духовные книги')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Верифицирован')),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('image_hash', models.CharField(blank=True, db_index=True, help_text='Perceptual hash для проверки на дубликаты', max_length=64, null=True, verbose_name='Хеш изображения')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('profiles_viewed', models.IntegerField(default=0)),
                ('likes_given', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сеанс пользователя',
                'verbose_name_plural': 'Сеансы пользователей',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view_profile', 'Просмотр профиля'), ('like', 'Лайк'), ('message', 'Сообщение'), ('search', 'Поиск'), ('edit_profile', 'Редактирование профиля')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.usersession')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ViewedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.usersession')),
            ],
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='profiles_co_status_47c0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reported_user', 'status'], name='profiles_co_reporte_670deb_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user_from', 'user_to'], name='profiles_li_user_fr_dd7c53_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user_to', 'created_at'], name='profiles_li_user_to_cb11ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(check=models.Q(('user_from', models.F('user_to')), _negated=True), name='cannot_like_yourself'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='profiles_me_sender__681d56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='profiles_me_receive_59e595_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='profiles_no_recipie_d94d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='profiles_po_status_62d660_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'active', 'created_at'], name='profiles_co_post_id_fdabf3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'active'], name='profiles_co_parent__1bf58e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-created_at'], name='profiles_us_created_d96714_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender', 'city'], name='profiles_us_gender_3d448d_idx'),
        ),
    ]
