# Generated by Django 5.0.7 on 2025-11-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Взята на рассмотрение'), ('in_progress', 'Рассматривается'), ('resolved', 'Разрешённый конфликт (Отдельно вы получите сообщение-отчет о жалобе)')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='profiles.complaint', verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='new_status',
            field=models.CharField(max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='complaintlog',
            name='old_status',
            field=models.CharField(max_length=20, verbose_name='Старый статус'),
        ),
    ]
