# Generated by Django 5.0.14 on 2025-11-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_notification_content_type_notification_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('logout', 'Выход'), ('timeout', 'Таймаут'), ('manual', 'Ручное завершение')], default='logout', max_length=20, verbose_name='Действие')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('no_active_session', 'Нет активной сессии'), ('error', 'Ошибка')], default='completed', max_length=30, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ сессии')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог сессии',
                'verbose_name_plural': 'Логи сессий',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'status', 'timestamp'], name='profiles_se_user_id_0097de_idx')],
            },
        ),
    ]
