# Generated by Django 5.0.14 on 2025-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_sessionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_pics/%Y/%m/%d/', verbose_name='Фотография профиля'),
        ),
    ]
